#!/bin/sh

#================================================================
# extfxmantotxt
# Convert man (troff-andoc) into plain text.
#================================================================

# check arguments
if [ $# -lt 1 ]; then
  echo "Usage: $0 INFILE [OUTFILE]" 1>&2
  exit 1
fi

infile="$1"
outfile="$2"
if [ -n "$ESTORIGFILE" ] && [ -f "$ESTORIGFILE" ]; then
  infile="$ESTORIGFILE"
fi

if [ -n "$output" ]; then
  exec >"$output"
fi


# output the result
MANWIDTH=262144 man "$infile" 2> "/dev/null" | col -b | tr '\t' ' '

# exit normally
exit 0

